### ISSUE TITLE
Crash on iOS 9

### ISSUE THREAD

**Issue by miraclebg** [paypal/PayPal-iOS-SDK#297]
I've been experiencing this several times.

Before i upgraded to iOS Beta 2 it appeared just sometimes - but now - i can't get passed it at all.

Every time i try to open the payment screen it crashes.

```
2015-07-06 20:16:22:781 EKaiwaNowBeta[53015:70b] PayPal config initialized
2015-07-06 20:16:22:781 EKaiwaNowBeta[53015:70b] DEBUG: PayPal iOS SDK version: PayPal iOS SDK 2.11.0 (/Users/mkovachev/sworkspace/kaiwanow-ios/kaiwanow-ios/AppController.m:2376)
2015-07-06 20:16:22.789 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "ebay://" - error: "This app is not allowed to query for scheme ebay"
2015-07-06 20:16:22.790 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "fb267453465127://" - error: "This app is not allowed to query for scheme fb267453465127"
2015-07-06 20:16:22.791 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "ADX1140://" - error: "This app is not allowed to query for scheme ADX1140"
2015-07-06 20:16:22.791 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "ppclient://" - error: "This app is not allowed to query for scheme ppclient"
2015-07-06 20:16:22.792 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "paypal://" - error: "This app is not allowed to query for scheme paypal"
2015-07-06 20:16:22.793 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "paypal-local-search://" - error: "This app is not allowed to query for scheme paypal-local-search"
2015-07-06 20:16:22.794 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "halfdotcom://" - error: "This app is not allowed to query for scheme halfdotcom"
2015-07-06 20:16:22.795 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "redlaser://" - error: "This app is not allowed to query for scheme redlaser"
2015-07-06 20:16:22.795 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "where://" - error: "This app is not allowed to query for scheme where"
2015-07-06 20:16:22.796 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "ebaymotors://" - error: "This app is not allowed to query for scheme ebaymotors"
2015-07-06 20:16:22.797 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "fb164705030244434://" - error: "This app is not allowed to query for scheme fb164705030244434"
2015-07-06 20:16:22.798 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "ebayfashion://" - error: "This app is not allowed to query for scheme ebayfashion"
2015-07-06 20:16:22.798 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "stubhub://" - error: "This app is not allowed to query for scheme stubhub"
2015-07-06 20:16:22.799 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "sdc://" - error: "This app is not allowed to query for scheme sdc"
2015-07-06 20:16:22.800 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "fb299473330131984://" - error: "This app is not allowed to query for scheme fb299473330131984"
2015-07-06 20:16:22.800 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "paypalhere://" - error: "This app is not allowed to query for scheme paypalhere"
2015-07-06 20:16:22.801 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "ebaynow://" - error: "This app is not allowed to query for scheme ebaynow"
2015-07-06 20:16:22.802 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"
2015-07-06 20:16:22.803 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "loch://" - error: "This app is not allowed to query for scheme loch"
2015-07-06 20:16:22.804 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "fb1b1cca46cd75ebc75ad67e6904d5f176://" - error: "This app is not allowed to query for scheme fb1b1cca46cd75ebc75ad67e6904d5f176"
2015-07-06 20:16:22.805 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "hotspotshield://" - error: "This app is not allowed to query for scheme hotspotshield"
2015-07-06 20:16:22.806 EKaiwaNowBeta[53015:13381980] -canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"
2015-07-06 20:16:22:858 EKaiwaNowBeta[53015:70b] ERROR: Uncaught exception: -[NSTaggedPointerString getCharacters:range:]: Range {0, 7} out of bounds; string length 4

Stacktrace:

(
	0   CoreFoundation                      0x0000000108c24ca5 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000108699dcd objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108c24bdd +[NSException raise:format:] + 205
	3   CoreFoundation                      0x0000000108c1083a -[NSTaggedPointerString getCharacters:range:] + 394
	4   CoreFoundation                      0x0000000108afbf7a CFStringCompareWithOptionsAndLocale + 2970
	5   CoreFoundation                      0x0000000108c1118b -[NSTaggedPointerString compare:options:range:locale:] + 219
	6   Foundation                          0x0000000108238027 -[NSString compare:options:range:] + 29
	7   EKaiwaNowBeta                       0x00000001031d3bbf __53-[PPZebraLocalizer localizeString:adaptedForCountry:]_block_invoke + 60
	8   CoreFoundation                      0x0000000108b5284b -[NSArray indexOfObject:inSortedRange:options:usingComparator:] + 491
	9   EKaiwaNowBeta                       0x00000001031d3904 -[PPZebraLocalizer localizeString:adaptedForCountry:] + 426
	10  EKaiwaNowBeta                       0x00000001031d4374 PPZebraLocalizedStringWithAlert + 1044
	11  EKaiwaNowBeta                       0x00000001031c26d3 +[PPZebraUI localizedStringForKey:adaptedForCountry:] + 140
	12  EKaiwaNowBeta                       0x00000001031c3711 +[PPZebraUI cancelBarButtonWithTarget:withAction:] + 88
	13  EKaiwaNowBeta                       0x00000001031b1531 -[PPDeviceCheckViewController viewDidLoad] + 292
	14  UIKit                               0x00000001070013f6 -[UIViewController loadViewIfRequired] + 871
	15  UIKit                               0x0000000107001765 -[UIViewController view] + 27
	16  UIKit                               0x000000010704e6ba -[UINavigationController preferredContentSize] + 194
	17  UIKit                               0x0000000106fd95ed -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 152
	18  UIKit                               0x0000000106fd5c3f __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 95
	19  UIKit                               0x0000000106e8a907 _runAfterCACommitDeferredBlocks + 317
	20  UIKit                               0x0000000106e9c091 _cleanUpAfterCAFlushAndRunDeferredBlocks + 95
	21  UIKit                               0x0000000106ea793c _afterCACommitHandler + 90
	22  CoreFoundation                      0x0000000108b4f0b7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	23  CoreFoundation                      0x0000000108b4f027 __CFRunLoopDoObservers + 391
	24  CoreFoundation                      0x0000000108b44b5b __CFRunLoopRun + 1147
	25  CoreFoundation                      0x0000000108b44458 CFRunLoopRunSpecific + 488
	26  GraphicsServices                    0x00000001095ffbca GraphicsServices + 52170
	27  UIKit                               0x0000000106e7f1c2 UIApplicationMain + 171
	28  EKaiwaNowBeta                       0x0000000102f73c00 main + 240
	29  libdyld.dylib                       0x000000010989f92d libdyld.dylib + 10541
)


libc++abi.dylib: terminate_handler unexpectedly threw an exception
```

**Comment by intelliot** [comment]
Thanks for reporting this issue! We've identified the problem and will be releasing a fix shortly.

**Comment by miraclebg** [comment]
Thanks a lot - i am trying to get passed it but so far i am failing.

If you have any sort of early beta in case it’s something that will take time i would kindly ask you to send it over.

Right now i am in the middle of a feature release / testing and this is basically blocking everything - can’t get past the payment process.

Thank you!

___________________________________
Martin Kovachev - IT Manager,
Nimasystems Ltd
Tel.: +359 896 610 876
Fax: +359 32 395 283
Skype: miracle_bg
E-Mail: miracle@nimasystems.com
Website: http://www.nimasystems.com

**Comment by tomwhipple** [comment]
We'll track this as issue #290.

**Comment by miraclebg** [comment]
Alright, thanks!

**Comment by intelliot** [comment]
@miraclebg I believe this specific crash should be fixed in 2.11.1. Could you give it a try and let me know? https://github.com/paypal/PayPal-iOS-SDK/releases/2.11.1

Thanks!

**Comment by miraclebg** [comment]
@intelliot It is not crashing now - but there is another issue related to the new SSL requirements imposed by Apple - i see in the log the connections to PayPal are being rejected - probably because i am using the sandbox servers.

Is there a way to override this for the moment by specifying exclusions in: NSAppTransportSecurity?
![screen shot 2015-07-10 at 1 55 49](https://cloud.githubusercontent.com/assets/126405/8608806/298f2662-26a7-11e5-8989-f71e6f9988b2.png)
![screen shot 2015-07-10 at 1 55 37](https://cloud.githubusercontent.com/assets/126405/8608807/29b6807c-26a7-11e5-9d10-6ace4bb3c101.png)
![screen shot 2015-07-10 at 1 55 33](https://cloud.githubusercontent.com/assets/126405/8608808/29b794d0-26a7-11e5-9ef4-767d10a5412f.png)

**Comment by miraclebg** [comment]
Just to confirm - this issue is still not fixed, see crash below:

`2015-08-10 15:47:50:240 EKaiwaNowBeta[753:b07] PayPal config initialized
2015-08-10 15:47:50:240 EKaiwaNowBeta[753:b07] DEBUG: PayPal iOS SDK version: PayPal iOS SDK 2.11.1 (/Users/mkovachev/sworkspace/kaiwanow-ios/kaiwanow-ios/AppController.m:2376)
2015-08-10 15:47:50.294 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ebay://" - error: "This app is not allowed to query for scheme ebay"
2015-08-10 15:47:50.295 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "fb267453465127://" - error: "This app is not allowed to query for scheme fb267453465127"
2015-08-10 15:47:50.299 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ADX1140://" - error: "This app is not allowed to query for scheme ADX1140"
2015-08-10 15:47:50.301 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ppclient://" - error: "This app is not allowed to query for scheme ppclient"
2015-08-10 15:47:50.306 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "paypal://" - error: "This app is not allowed to query for scheme paypal"
2015-08-10 15:47:50.308 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "paypal-local-search://" - error: "This app is not allowed to query for scheme paypal-local-search"
2015-08-10 15:47:50.309 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "halfdotcom://" - error: "This app is not allowed to query for scheme halfdotcom"
2015-08-10 15:47:50.310 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "redlaser://" - error: "This app is not allowed to query for scheme redlaser"
2015-08-10 15:47:50.315 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "where://" - error: "This app is not allowed to query for scheme where"
2015-08-10 15:47:50.316 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ebaymotors://" - error: "This app is not allowed to query for scheme ebaymotors"
2015-08-10 15:47:50.316 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "fb164705030244434://" - error: "This app is not allowed to query for scheme fb164705030244434"
2015-08-10 15:47:50.317 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ebayfashion://" - error: "This app is not allowed to query for scheme ebayfashion"
2015-08-10 15:47:50.318 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "stubhub://" - error: "This app is not allowed to query for scheme stubhub"
2015-08-10 15:47:50.321 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "sdc://" - error: "This app is not allowed to query for scheme sdc"
2015-08-10 15:47:50.322 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "fb299473330131984://" - error: "This app is not allowed to query for scheme fb299473330131984"
2015-08-10 15:47:50.324 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "paypalhere://" - error: "This app is not allowed to query for scheme paypalhere"
2015-08-10 15:47:50.325 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ebaynow://" - error: "This app is not allowed to query for scheme ebaynow"
2015-08-10 15:47:50.326 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"
2015-08-10 15:47:50.326 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "loch://" - error: "This app is not allowed to query for scheme loch"
2015-08-10 15:47:50.327 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "fb1b1cca46cd75ebc75ad67e6904d5f176://" - error: "This app is not allowed to query for scheme fb1b1cca46cd75ebc75ad67e6904d5f176"
2015-08-10 15:47:50.328 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "hotspotshield://" - error: "This app is not allowed to query for scheme hotspotshield"
2015-08-10 15:47:50.340 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"
2015-08-10 15:47:51.103 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ebay://" - error: "This app is not allowed to query for scheme ebay"
2015-08-10 15:47:51.104 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "fb267453465127://" - error: "This app is not allowed to query for scheme fb267453465127"
2015-08-10 15:47:51.105 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ADX1140://" - error: "This app is not allowed to query for scheme ADX1140"
2015-08-10 15:47:51.107 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ppclient://" - error: "This app is not allowed to query for scheme ppclient"
2015-08-10 15:47:51.109 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "paypal://" - error: "This app is not allowed to query for scheme paypal"
2015-08-10 15:47:51.110 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "paypal-local-search://" - error: "This app is not allowed to query for scheme paypal-local-search"
2015-08-10 15:47:51.111 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "halfdotcom://" - error: "This app is not allowed to query for scheme halfdotcom"
2015-08-10 15:47:51.112 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "redlaser://" - error: "This app is not allowed to query for scheme redlaser"
2015-08-10 15:47:51.115 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "where://" - error: "This app is not allowed to query for scheme where"
2015-08-10 15:47:51.116 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ebaymotors://" - error: "This app is not allowed to query for scheme ebaymotors"
2015-08-10 15:47:51.117 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "fb164705030244434://" - error: "This app is not allowed to query for scheme fb164705030244434"
2015-08-10 15:47:51.118 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ebayfashion://" - error: "This app is not allowed to query for scheme ebayfashion"
2015-08-10 15:47:51.119 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "stubhub://" - error: "This app is not allowed to query for scheme stubhub"
2015-08-10 15:47:51.120 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "sdc://" - error: "This app is not allowed to query for scheme sdc"
2015-08-10 15:47:51.122 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "fb299473330131984://" - error: "This app is not allowed to query for scheme fb299473330131984"
2015-08-10 15:47:51.123 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "paypalhere://" - error: "This app is not allowed to query for scheme paypalhere"
2015-08-10 15:47:51.125 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "ebaynow://" - error: "This app is not allowed to query for scheme ebaynow"
2015-08-10 15:47:51.126 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"
2015-08-10 15:47:51.131 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "loch://" - error: "This app is not allowed to query for scheme loch"
2015-08-10 15:47:51.132 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "fb1b1cca46cd75ebc75ad67e6904d5f176://" - error: "This app is not allowed to query for scheme fb1b1cca46cd75ebc75ad67e6904d5f176"
2015-08-10 15:47:51.133 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "hotspotshield://" - error: "This app is not allowed to query for scheme hotspotshield"
2015-08-10 15:47:51.141 EKaiwaNowBeta[753:160389] -canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"
2015-08-10 15:47:52:626 EKaiwaNowBeta[753:b07] ERROR: Uncaught exception: -[NSTaggedPointerString getCharacters:range:]: Range {0, 14} out of bounds; string length 9

Stacktrace:

(
	0   CoreFoundation                      0x0000000182bd5aac <redacted> + 148
	1   libobjc.A.dylib                     0x000000019761ff80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182bd59dc <redacted> + 0
	3   CoreFoundation                      0x0000000182bbd01c <redacted> + 248
	4   CoreFoundation                      0x0000000182ac7bb4 CFStringCompareWithOptionsAndLocale + 2328
	5   CoreFoundation                      0x0000000182bbd7c8 <redacted> + 244
	6   EKaiwaNowBeta                       0x0000000100603c90 __52-[CardIOLocalizer localizeString:adaptedForCountry:]_block_invoke + 64
	7   CoreFoundation                      0x0000000182b0dc04 <redacted> + 444
	8   EKaiwaNowBeta                       0x00000001006039dc -[CardIOLocalizer localizeString:adaptedForCountry:] + 468
	9   EKaiwaNowBeta                       0x00000001006045bc CardIOLocalizedStringWithAlert + 1300
	10  EKaiwaNowBeta                       0x0000000100604764 CardIOLocalizedString + 68
	11  EKaiwaNowBeta                       0x00000001005ec114 +[CardIOCreditCardInfo displayStringForCardType:usingLanguageOrLocale:] + 172
	12  EKaiwaNowBeta                       0x00000001005ac16c -[PPSelectPayMethodViewControllerIOS7 updateTableToConfirm:] + 576
	13  EKaiwaNowBeta                       0x00000001005abe2c -[PPSelectPayMethodViewControllerIOS7 refreshTable:] + 120
	14  EKaiwaNowBeta                       0x00000001005abea4 -[PPSelectPayMethodViewControllerIOS7 viewWillAppear:] + 104
	15  UIKit                               0x00000001880fecf8 <redacted> + 628
	16  UIKit                               0x00000001880fea6c <redacted> + 156
	17  UIKit                               0x0000000188292e10 <redacted> + 1044
	18  UIKit                               0x00000001881a24c8 <redacted> + 688
	19  UIKit                               0x00000001881a21a4 <redacted> + 60
	20  UIKit                               0x00000001881a210c <redacted> + 208
	21  UIKit                               0x00000001880e2614 <redacted> + 644
	22  QuartzCore                          0x00000001878f1f14 <redacted> + 148
	23  QuartzCore                          0x00000001878ecb20 <redacted> + 292
	24  QuartzCore                          0x00000001878ec9e0 <redacted> + 32
	25  QuartzCore                          0x00000001878ec07c <redacted> + 252
	26  QuartzCore                          0x00000001878ebdd0 <redacted> + 516
	27  QuartzCore                          0x00000001878e54bc <redacted> + 80
	28  CoreFoundation                      0x0000000182b8c768 <redacted> + 32
	29  CoreFoundation                      0x0000000182b8a50c <redacted> + 372
	30  CoreFoundation                      0x0000000182b8a93c <redacted> + 928
	31  CoreFoundation                      0x0000000182ab98a0 CFRunLoopRunSpecific + 384
	32  GraphicsServices                    0x000000018db14088 GSEventRunModal + 180
	33  UIKit                               0x000000018814e0d4 UIApplicationMain + 204
	34  EKaiwaNowBeta                       0x0000000100337bcc main + 284
	35  libdyld.dylib                       0x0000000197e6e8b8 <redacted> + 4
)


2015-08-10 15:47:52.628 EKaiwaNowBeta[753:160389] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 14} out of bounds; string length 9'
*** First throw call stack:
(0x182bd5a94 0x19761ff80 0x182bd59dc 0x182bbd01c 0x182ac7bb4 0x182bbd7c8 0x100603c90 0x182b0dc04 0x1006039dc 0x1006045bc 0x100604764 0x1005ec114 0x1005ac16c 0x1005abe2c 0x1005abea4 0x1880fecf8 0x1880fea6c 0x188292e10 0x1881a24c8 0x1881a21a4 0x1881a210c 0x1880e2614 0x1878f1f14 0x1878ecb20 0x1878ec9e0 0x1878ec07c 0x1878ebdd0 0x1878e54bc 0x182b8c768 0x182b8a50c 0x182b8a93c 0x182ab98a0 0x18db14088 0x18814e0d4 0x100337bcc 0x197e6e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException`
