### ISSUE TITLE
System Error: PAYER_ACTION_REQUIRED

### ISSUE THREAD

**Issue by nileshpunjabi** [paypal/PayPal-iOS-SDK#353]
Please check this link for more detail.
http://stackoverflow.com/q/33264474

**Comment by tomwhipple** [comment]
@nileshpunjabi my guess is that there is something associated with your account that is triggering an error case. 

We'll work to fix the error messaging, but you may also want to work with [Merchant support](https://www.paypal-techsupport.com/app/ask) to resolve the root cause configuration problem.

**Comment by amourinho** [comment]
I'm having the exact same issue as nileshpunjabi. Works flawlessly on the Android version of the app I have developed, using the same accounts and whatnot. However iOS returns with this same error. Looking for help/answers as this is keeping me from publishing my app to the itunes sture.

**Comment by bluk** [comment]
@amourinho Can you give a PayPal-Debug-Id for a failing request? This helps narrow down the specific cause for your error. Thanks!

**Comment by amourinho** [comment]
Honestly, I wish I had an answer for you (or a debug-id) @bluk. Without changing any code, the charges have been able to be processed. I get a "Completed" notification now. However for over an hour or two I had been trying to figure out this issue, and in the last 5 minutes it seems to have resolved itself. Which kind of worries me.

**Comment by amourinho** [comment]
Never mind, seems to have shown up again... Here is a debug id from a recent attempt "062083094c859"

Any pointers would greatly help.

**Comment by Naiko** [comment]
The same issue has suddenly started occurring on my production app. Multiple users have recently started reported not being able to make purchases through PayPal because of this issue even though their payment details are valid.

I was able to reproduce it and got the following debug id: f1b3456a42349

Can you let us know if any progress are made on this issue? This is quite a big deal as users aren't able to make purchases. 

Many thanks

**Comment by bluk** [comment]
@Naiko @amourinho I've contacted a team to help do further investigation, but I also urge you to contact [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) which may be able to help further with the root cause.

**Comment by Naiko** [comment]
Great thank you for the link, I couldn't find that support page. I've created a ticket.

**Comment by hardikmamtora** [comment]
I have same issue. Can any one help me out for this?

**Comment by gurumaheshPCS** [comment]
i had the same issue..  Debug-ID: 8a4645b32a92a

**Comment by ppmtscory** [comment]
All,
We found out what the issue was and @bluk was able to make the changes to the affected code.  Either him or I will update here once everything is able to be pushed out.

**Comment by puneet1106** [comment]
Hi I am also facing the same issue.It is working only once in the noon and after that it is showing me the same alert "PAYER_ACTION_REQUIRED". I am working in sandbox mode. It is working fine in android but giving issue in iOS. My debug id is : 148dc3cdd5954

**Comment by zsmzhu** [comment]
Hi i have got the same issue too, PAYER_ACTION_REQUIRED, i am working in live mode. it's working in android and web. only when I try to pay in iOS sdk it's show me the alert "PAYER_ACTION_REQUIRED"

**Comment by nicolo** [comment]
Also seeing this. The same paypal account that gets the error does not get the error when using the android sdk. Can we get an status update on this?

**Comment by bluk** [comment]
We are pushing for a server side code change which should resolve the issue (without any need for a client SDK update). We will update this issue when the fix is deployed.

**Comment by tomwhipple** [comment]
Adding to what @bluk said, we expect to be able to push the fix by end of day tomorrow. (Friday 10/29 PDT)

**Comment by puneet1106** [comment]
@tomwhipple Hi Guys, any updates?Fixed?

**Comment by tomwhipple** [comment]
Update: The fix deployment has been delayed. We are hopeful it will be available tomorrow evening (Saturday 10/31, PDT).

... and it looks like I misstated the date in my previous update. The fix was originally scheduled to be deployed this evening, Friday **10/30**.

**Comment by amourinho** [comment]
Thank-you for the update's @tomwhipple and @bluk. Look forward to having my app functioning properly again soon.

**Comment by tomwhipple** [comment]
Unfortunately this release is being pushed back to early next week. At this point I hesitate to be more specific, but we will keep you posted.

**Comment by zsmzhu** [comment]
hope to see the fixed next week, because not only sandbox but also live mode occurred this problem.
Many thanks.

**Comment by tomwhipple** [comment]
The fix was pushed live last night. If this persists, please reopen.

**Comment by kaderkayten** [comment]
I am facing this issue and i updated to the latest sdk but still did not solved the problem.

2016-08-17 13:51:54.207 UnitedTaxi-Passenger[330:113982] PayPal SDK: Request has failed with error: PAYER_ACTION_REQUIRED - System error (PAYER_ACTION_REQUIRED). Please try again later. (400) | PayPal Debug-ID: dde48de279651, dde48de279651 [sandbox, PayPal iOS SDK 2.14.5]

**Comment by ppmtscory** [comment]
@kaderkayten your buyer account wasn't fully set up.  The email address wasn't confirmed.  I confirmed that manually and also manually verified the account so it should be good to go now.  For future reference, always create your sandbox accounts in the [Dev Portal](https://developer.paypal.com) so that all of the proper account settings and funding instruments are set.  Also, if you need anything further, please reach out to our [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) team as this is not an SDK issue.

**Comment by vittorioscocca** [comment]
I have the same problem:

PayPal SDK: Request has failed with error: PAYER_ACTION_REQUIRED - System error (PAYER_ACTION_REQUIRED). Please try again later. (400) | PayPal Debug-ID: 4ac1811cbedeb, 4ac1811cbedeb [sandbox, PayPal iOS SDK 2.17.0]
