### ISSUE TITLE
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: a59fc41eae8b, a59fc41eae8b [sandbox, PayPal iOS SDK 2.15.1]

### ISSUE THREAD

**Issue by floryday** [paypal/PayPal-iOS-SDK#462]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- PayPal iOS SDK Version: 2.15.1
- iOS Version and Device (iOS 8.x, iOS 9.3 on an iPhone 6s, etc.): iOS 9.3.5 on an iPhone 6s
- PayPal-Debug-ID(s) (from any logs): a59fc41eae8b

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by bluk** [comment]
Sandbox is currently having issues. Internal issue SRE-43143 is currently tracking this. Live production should remain unaffected. Sorry for the issues.

See https://github.com/paypal/PayPal-Android-SDK/issues/349 .

**Comment by bluk** [comment]
This issue should be resolved now. I was able to make a payment via the mobile SDK in sandbox. If you're still encountering any issues, please leave a comment or open a new issue. Thank you for your patience.

**Comment by sharathvatti** [comment]
@bluk  Still getting this error for me. :(

_PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: a05b4203b85f5, a05b4203b85f5 [sandbox, PayPal iOS SDK 2.15.1]
![simulator screen shot 21-sep-2016 11 05 19 am](https://cloud.githubusercontent.com/assets/15937805/18698929/83936486-7feb-11e6-8f73-83450dd7f31a.png)
_

**Comment by bluk** [comment]
@sharathvatti Thanks for the report. There is an internal ticket SRE-43154 to track this new issue. My apologies for the inconvenience.

**Comment by hoanghua** [comment]
I'm also getting the same error. May I ask if there could be a way to workaround this issue to test the PayPal payment? 
> PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: a90e67ed3a1d3, a90e67ed3a1d3 [sandbox, PayPal iOS SDK 2.11.4]

**Comment by bluk** [comment]
This issue should be resolved now. Thank you for your patience.

**Comment by shu-ua** [comment]
Did this bug fixed for now?
I still get this bug on sandbox.

**Log:**

> PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 6658630d47b78, 6658630d47b78 [sandbox, PayPal iOS SDK 2.15.1]

**Comment by bluk** [comment]
@shu-ua It appears there was a sandbox deployment last night that caused some timeout issues. I was able to make a few payments this morning using this SDK in sandbox. Can you please try again and if it still fails, can you please open a new issue?

**Comment by liz1027** [comment]
I am also getting this error: PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: 18a5f4007f484, 18a5f4007f484 [live, PayPal iOS SDK 2.16.1]

**Comment by bluk** [comment]
@liz1027 Since this is a live production issue, please contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) who should be able to help.
